# Generated by Django 3.2.4 on 2021-06-21 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hexagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('overview', models.TextField()),
                ('sequence', models.TextField()),
                ('note', models.TextField()),
                ('judgement_poem', models.TextField()),
                ('judgement', models.TextField()),
                ('image_poem', models.TextField()),
                ('image', models.TextField()),
                ('emphasis1_poem', models.TextField()),
                ('emphasis1', models.TextField()),
                ('emphasis2_poem', models.TextField()),
                ('emphasis2', models.TextField()),
                ('emphasis3_poem', models.TextField()),
                ('emphasis3', models.TextField()),
                ('emphasis4_poem', models.TextField()),
                ('emphasis4', models.TextField()),
                ('emphasis5_poem', models.TextField()),
                ('emphasis5', models.TextField()),
                ('emphasis6_poem', models.TextField()),
                ('emphasis6', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Fortune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('relevance', models.IntegerField()),
                ('notes', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iChing.hexagram')),
            ],
        ),
    ]
