# Generated by Django 3.2.4 on 2021-06-21 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iChing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hexagram',
            name='digits',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hexagram',
            name='number',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fortune',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fortune',
            name='relevance',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='hexagram',
            name='emphasis1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hexagram',
            name='emphasis1_poem',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hexagram',
            name='emphasis2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hexagram',
            name='emphasis2_poem',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hexagram',
            name='emphasis3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hexagram',
            name='emphasis3_poem',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hexagram',
            name='emphasis4',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hexagram',
            name='emphasis4_poem',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hexagram',
            name='emphasis5',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hexagram',
            name='emphasis5_poem',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hexagram',
            name='emphasis6',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hexagram',
            name='emphasis6_poem',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hexagram',
            name='image',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hexagram',
            name='image_poem',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hexagram',
            name='judgement',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hexagram',
            name='judgement_poem',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hexagram',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hexagram',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hexagram',
            name='overview',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hexagram',
            name='sequence',
            field=models.TextField(blank=True),
        ),
    ]
