# Generated by Django 3.2.4 on 2021-06-21 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iChing', '0002_auto_20210621_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='hexagram',
            name='emphasisall',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hexagram',
            name='emphasisall_poem',
            field=models.TextField(blank=True),
        ),
    ]
