# Generated by Django 3.2.4 on 2021-06-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iChing', '0003_auto_20210621_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='fortune',
            name='digits',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
