# Generated by Django 3.2.4 on 2021-06-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iChing', '0004_fortune_digits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fortune',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fortune',
            name='relevance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
